name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        run: |
          pipx install uv

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ hashFiles('**/requirements.txt', '**/pyproject.toml') }}
          restore-keys: |
            uv-${{ runner.os }}-

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then uv pip install -r requirements.txt; fi
          uv pip install pre-commit ruff black mypy pytest pytest-cov

      - name: Ruff (lint)
        run: uv run ruff check .

      - name: Ruff (format check)
        run: uv run ruff format --check .

      - name: Black (format check)
        run: uv run black --check .

      - name: Mypy (type check)
        run: uv run mypy .

      - name: Tests
        run: uv run pytest -q --cov=server --cov=scripts --cov-report=term-missing --cov-fail-under=90

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            .coverage
            htmlcov/
